package com.self.activity.model;

import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
@ApiModel(value="证件信息",description="证件信息")
public class Certification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="证件唯一id",notes="证件唯一id")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.customer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="客户id",notes="客户id")
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.type_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="证件类型ID",notes="证件类型Id")
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.code
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="证件号码",notes="证件号码")
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.expiry_date
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="过期日期",notes="过期日期")
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="版本",notes="版本",hidden=true)
    private Integer versionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="创建人ID",notes="创建人ID")
    private Long createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="创建时间",notes="创建时间",hidden=true)
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="更新人ID",notes="更新人ID")
    private Long lastUpdatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="更新时间",notes="更新时间",hidden=true)
    private Date lastUpdatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_certification.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="删除标志",notes="删除标志",hidden=true)
    private Boolean deletedFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.id
     *
     * @return the value of cu_certification.id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.id
     *
     * @param id the value for cu_certification.id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.customer_id
     *
     * @return the value of cu_certification.customer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.customer_id
     *
     * @param customerId the value for cu_certification.customer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.type_id
     *
     * @return the value of cu_certification.type_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.type_id
     *
     * @param typeId the value for cu_certification.type_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.code
     *
     * @return the value of cu_certification.code
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.code
     *
     * @param code the value for cu_certification.code
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.expiry_date
     *
     * @return the value of cu_certification.expiry_date
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.expiry_date
     *
     * @param expiryDate the value for cu_certification.expiry_date
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.version_no
     *
     * @return the value of cu_certification.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.version_no
     *
     * @param versionNo the value for cu_certification.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.created_by_id
     *
     * @return the value of cu_certification.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.created_by_id
     *
     * @param createdById the value for cu_certification.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCreatedById(Long createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.created_time
     *
     * @return the value of cu_certification.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.created_time
     *
     * @param createdTime the value for cu_certification.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.last_updated_by_id
     *
     * @return the value of cu_certification.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getLastUpdatedById() {
        return lastUpdatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.last_updated_by_id
     *
     * @param lastUpdatedById the value for cu_certification.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLastUpdatedById(Long lastUpdatedById) {
        this.lastUpdatedById = lastUpdatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.last_updated_time
     *
     * @return the value of cu_certification.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.last_updated_time
     *
     * @param lastUpdatedTime the value for cu_certification.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_certification.deleted_flag
     *
     * @return the value of cu_certification.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_certification.deleted_flag
     *
     * @param deletedFlag the value for cu_certification.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }
}