package com.self.activity.model;

import java.util.Date;

import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
@ApiModel(value="Customer",description="客户基本信息")
public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="客户唯一id",notes="客户唯一id")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.regist_org_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="注册机构",notes="注册机构")
    private Integer registOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.type_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="客户类型",notes="客户类型",hidden=true)
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.code
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @NotBlank(message="10000")
    @Size(min=3,max=10,message="10000,3,10")
    @ApiModelProperty(value="客户编码",notes="客户编码",hidden=true)
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.name
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="姓名",notes="客户姓名")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.des
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="描述",notes="描述")
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.sex_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="性别ID",notes="性别ID")
    private Integer sexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.birthday
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="出生日期",notes="出生日期",dataType="date")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.id_card_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="身份证号",notes="身份证号")
    @Pattern(regexp="^[1-9]\\d{5}[1-9]\\d{3}((0\\d)|(1[0-2]))(([0|1|2]\\d)|3[0-1])((\\d{4})|\\d{3}[A-Za-z])$",message="10040")
    private String idCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.email
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="电子邮箱",notes="电子邮箱")
    @Email(message="10050")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.mobile
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="移动电话",notes="移动电话")
    @Pattern(regexp="^((13[0-9])|(14[0-9])|(15[0-9])|(17[0-9])|(18[0-9]))\\d{8}$",message="10060")
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.tel
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="固定电话",notes="固定电话")
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.country_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="国籍ID",notes="国籍ID",hidden=true)
    private Integer countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.nation_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="民族ID",notes="民族ID",hidden=true)
    private Integer nationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.language_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="语种Id",notes="语种ID",hidden=true)
    private Integer languageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.politics_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="政治面貌ID",notes="政治面貌ID")
    private Integer politicsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.education_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="教育程度ID",notes="教育程度ID")
    private Integer educationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.degree_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="学位ID",notes="学位ID")
    private Integer degreeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.occupation_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="职业Id",notes="职业ID")
    private Integer occupationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.org_name
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="单位名称",notes="单位名称")
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.married_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="婚姻状况",notes="婚姻状况")
    private Short marriedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.regist_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="注册时间",notes="注册时间")
    private Date registTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.main_index_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="主索引标志",notes="主索引标志")
    private Boolean mainIndexFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.spell_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="拼音简称",notes="拼音简称")
    private String spellNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.wubi_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="五笔简称",notes="五笔简称")
    private String wubiNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.nickname
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="昵称/别名",notes="昵称/别名")
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.livestate_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="居住情况",notes="居住情况")
    private Integer livestateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.liveorgstate_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
     @ApiModelProperty(value="养老机构居住状态编码",notes="养老机构居住状态编码")
    private Integer liveorgstateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.occupation_other
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="其他职业说明",notes="其他职业说明")
    private String occupationOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.religion_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="宗教信仰编码",notes="宗教信仰编码")
    private Integer religionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.interculture_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="兴趣爱好(文化娱乐)编码",notes="兴趣爱好(文化娱乐)编码")
    private String intercultureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.intersports_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="兴趣爱好(健身运动)编码",notes="兴趣爱好(健身运动)编码")
    private String intersportsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.abo_blood_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="ABO血型",notes="ABO血型")
    private Integer aboBloodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.rh_blood_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="RH血型",notes="RH血型")
    private Integer rhBloodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.resident_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="居民标志",notes="居民标志")
    private Boolean residentFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.high_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="高客标志",notes="高客标志")
    private Boolean highFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.employee_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="员工标志",notes="员工标志")
    private Boolean employeeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="版本",notes="版本",hidden=true)
    private Integer versionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="创建人ID",notes="创建人ID")
    private Long createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="创建时间",notes="创建时间",hidden=true)
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="更新人Id",notes="更新人Id")
    private Long lastUpdatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="更新时间",notes="更新时间",hidden=true)
    private Date lastUpdatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    @ApiModelProperty(value="删除标志",notes="删除标志",hidden=true)
    private Boolean deletedFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.id
     *
     * @return the value of cu_customer.id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.id
     *
     * @param id the value for cu_customer.id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.regist_org_id
     *
     * @return the value of cu_customer.regist_org_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getRegistOrgId() {
        return registOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.regist_org_id
     *
     * @param registOrgId the value for cu_customer.regist_org_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setRegistOrgId(Integer registOrgId) {
        this.registOrgId = registOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.type_id
     *
     * @return the value of cu_customer.type_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.type_id
     *
     * @param typeId the value for cu_customer.type_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.code
     *
     * @return the value of cu_customer.code
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.code
     *
     * @param code the value for cu_customer.code
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.name
     *
     * @return the value of cu_customer.name
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.name
     *
     * @param name the value for cu_customer.name
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.des
     *
     * @return the value of cu_customer.des
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.des
     *
     * @param des the value for cu_customer.des
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setDes(String des) {
        this.des = des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.sex_id
     *
     * @return the value of cu_customer.sex_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getSexId() {
        return sexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.sex_id
     *
     * @param sexId the value for cu_customer.sex_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setSexId(Integer sexId) {
        this.sexId = sexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.birthday
     *
     * @return the value of cu_customer.birthday
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.birthday
     *
     * @param birthday the value for cu_customer.birthday
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.id_card_no
     *
     * @return the value of cu_customer.id_card_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.id_card_no
     *
     * @param idCardNo the value for cu_customer.id_card_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.email
     *
     * @return the value of cu_customer.email
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.email
     *
     * @param email the value for cu_customer.email
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.mobile
     *
     * @return the value of cu_customer.mobile
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.mobile
     *
     * @param mobile the value for cu_customer.mobile
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.tel
     *
     * @return the value of cu_customer.tel
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.tel
     *
     * @param tel the value for cu_customer.tel
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.country_id
     *
     * @return the value of cu_customer.country_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.country_id
     *
     * @param countryId the value for cu_customer.country_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.nation_id
     *
     * @return the value of cu_customer.nation_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getNationId() {
        return nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.nation_id
     *
     * @param nationId the value for cu_customer.nation_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setNationId(Integer nationId) {
        this.nationId = nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.language_id
     *
     * @return the value of cu_customer.language_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.language_id
     *
     * @param languageId the value for cu_customer.language_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.politics_id
     *
     * @return the value of cu_customer.politics_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getPoliticsId() {
        return politicsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.politics_id
     *
     * @param politicsId the value for cu_customer.politics_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setPoliticsId(Integer politicsId) {
        this.politicsId = politicsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.education_id
     *
     * @return the value of cu_customer.education_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getEducationId() {
        return educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.education_id
     *
     * @param educationId the value for cu_customer.education_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setEducationId(Integer educationId) {
        this.educationId = educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.degree_id
     *
     * @return the value of cu_customer.degree_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getDegreeId() {
        return degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.degree_id
     *
     * @param degreeId the value for cu_customer.degree_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setDegreeId(Integer degreeId) {
        this.degreeId = degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.occupation_id
     *
     * @return the value of cu_customer.occupation_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getOccupationId() {
        return occupationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.occupation_id
     *
     * @param occupationId the value for cu_customer.occupation_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setOccupationId(Integer occupationId) {
        this.occupationId = occupationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.org_name
     *
     * @return the value of cu_customer.org_name
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.org_name
     *
     * @param orgName the value for cu_customer.org_name
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.married_flag
     *
     * @return the value of cu_customer.married_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Short getMarriedFlag() {
        return marriedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.married_flag
     *
     * @param marriedFlag the value for cu_customer.married_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setMarriedFlag(Short marriedFlag) {
        this.marriedFlag = marriedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.regist_time
     *
     * @return the value of cu_customer.regist_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getRegistTime() {
        return registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.regist_time
     *
     * @param registTime the value for cu_customer.regist_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setRegistTime(Date registTime) {
        this.registTime = registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.main_index_flag
     *
     * @return the value of cu_customer.main_index_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Boolean getMainIndexFlag() {
        return mainIndexFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.main_index_flag
     *
     * @param mainIndexFlag the value for cu_customer.main_index_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setMainIndexFlag(Boolean mainIndexFlag) {
        this.mainIndexFlag = mainIndexFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.spell_no
     *
     * @return the value of cu_customer.spell_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getSpellNo() {
        return spellNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.spell_no
     *
     * @param spellNo the value for cu_customer.spell_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setSpellNo(String spellNo) {
        this.spellNo = spellNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.wubi_no
     *
     * @return the value of cu_customer.wubi_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getWubiNo() {
        return wubiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.wubi_no
     *
     * @param wubiNo the value for cu_customer.wubi_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setWubiNo(String wubiNo) {
        this.wubiNo = wubiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.nickname
     *
     * @return the value of cu_customer.nickname
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.nickname
     *
     * @param nickname the value for cu_customer.nickname
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.livestate_id
     *
     * @return the value of cu_customer.livestate_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getLivestateId() {
        return livestateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.livestate_id
     *
     * @param livestateId the value for cu_customer.livestate_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLivestateId(Integer livestateId) {
        this.livestateId = livestateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.liveorgstate_id
     *
     * @return the value of cu_customer.liveorgstate_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getLiveorgstateId() {
        return liveorgstateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.liveorgstate_id
     *
     * @param liveorgstateId the value for cu_customer.liveorgstate_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLiveorgstateId(Integer liveorgstateId) {
        this.liveorgstateId = liveorgstateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.occupation_other
     *
     * @return the value of cu_customer.occupation_other
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getOccupationOther() {
        return occupationOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.occupation_other
     *
     * @param occupationOther the value for cu_customer.occupation_other
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setOccupationOther(String occupationOther) {
        this.occupationOther = occupationOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.religion_id
     *
     * @return the value of cu_customer.religion_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getReligionId() {
        return religionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.religion_id
     *
     * @param religionId the value for cu_customer.religion_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setReligionId(Integer religionId) {
        this.religionId = religionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.interculture_id
     *
     * @return the value of cu_customer.interculture_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getIntercultureId() {
        return intercultureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.interculture_id
     *
     * @param intercultureId the value for cu_customer.interculture_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setIntercultureId(String intercultureId) {
        this.intercultureId = intercultureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.intersports_id
     *
     * @return the value of cu_customer.intersports_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getIntersportsId() {
        return intersportsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.intersports_id
     *
     * @param intersportsId the value for cu_customer.intersports_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setIntersportsId(String intersportsId) {
        this.intersportsId = intersportsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.abo_blood_id
     *
     * @return the value of cu_customer.abo_blood_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getAboBloodId() {
        return aboBloodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.abo_blood_id
     *
     * @param aboBloodId the value for cu_customer.abo_blood_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setAboBloodId(Integer aboBloodId) {
        this.aboBloodId = aboBloodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.rh_blood_id
     *
     * @return the value of cu_customer.rh_blood_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getRhBloodId() {
        return rhBloodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.rh_blood_id
     *
     * @param rhBloodId the value for cu_customer.rh_blood_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setRhBloodId(Integer rhBloodId) {
        this.rhBloodId = rhBloodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.resident_flag
     *
     * @return the value of cu_customer.resident_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Boolean getResidentFlag() {
        return residentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.resident_flag
     *
     * @param residentFlag the value for cu_customer.resident_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setResidentFlag(Boolean residentFlag) {
        this.residentFlag = residentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.high_flag
     *
     * @return the value of cu_customer.high_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Boolean getHighFlag() {
        return highFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.high_flag
     *
     * @param highFlag the value for cu_customer.high_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setHighFlag(Boolean highFlag) {
        this.highFlag = highFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.employee_flag
     *
     * @return the value of cu_customer.employee_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Boolean getEmployeeFlag() {
        return employeeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.employee_flag
     *
     * @param employeeFlag the value for cu_customer.employee_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setEmployeeFlag(Boolean employeeFlag) {
        this.employeeFlag = employeeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.version_no
     *
     * @return the value of cu_customer.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.version_no
     *
     * @param versionNo the value for cu_customer.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.created_by_id
     *
     * @return the value of cu_customer.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.created_by_id
     *
     * @param createdById the value for cu_customer.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCreatedById(Long createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.created_time
     *
     * @return the value of cu_customer.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.created_time
     *
     * @param createdTime the value for cu_customer.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.last_updated_by_id
     *
     * @return the value of cu_customer.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getLastUpdatedById() {
        return lastUpdatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.last_updated_by_id
     *
     * @param lastUpdatedById the value for cu_customer.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLastUpdatedById(Long lastUpdatedById) {
        this.lastUpdatedById = lastUpdatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.last_updated_time
     *
     * @return the value of cu_customer.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.last_updated_time
     *
     * @param lastUpdatedTime the value for cu_customer.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.deleted_flag
     *
     * @return the value of cu_customer.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.deleted_flag
     *
     * @param deletedFlag the value for cu_customer.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }
}