package com.self.activity.model;

import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
@ApiModel(value="客户授权使用机构",description="客户授权使用机构")
public class OrgCustomer extends OrgCustomerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_org_customer.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="版本",notes="版本",hidden=true)
    private Integer versionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_org_customer.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="创建人Id",notes="创建人ID")
    private Long createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_org_customer.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="创建时间",notes="创建时间",hidden=true)
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_org_customer.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="更新人ID",notes="更新人ID")
    private Long lastUpdatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_org_customer.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="更新时间",notes="更新时间",hidden=true)
    private Date lastUpdatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_org_customer.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="删除标志",notes="删除标志",hidden=true)
    private Boolean deletedFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_org_customer.version_no
     *
     * @return the value of cu_org_customer.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_org_customer.version_no
     *
     * @param versionNo the value for cu_org_customer.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_org_customer.created_by_id
     *
     * @return the value of cu_org_customer.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_org_customer.created_by_id
     *
     * @param createdById the value for cu_org_customer.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCreatedById(Long createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_org_customer.created_time
     *
     * @return the value of cu_org_customer.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_org_customer.created_time
     *
     * @param createdTime the value for cu_org_customer.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_org_customer.last_updated_by_id
     *
     * @return the value of cu_org_customer.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getLastUpdatedById() {
        return lastUpdatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_org_customer.last_updated_by_id
     *
     * @param lastUpdatedById the value for cu_org_customer.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLastUpdatedById(Long lastUpdatedById) {
        this.lastUpdatedById = lastUpdatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_org_customer.last_updated_time
     *
     * @return the value of cu_org_customer.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_org_customer.last_updated_time
     *
     * @param lastUpdatedTime the value for cu_org_customer.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_org_customer.deleted_flag
     *
     * @return the value of cu_org_customer.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_org_customer.deleted_flag
     *
     * @param deletedFlag the value for cu_org_customer.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }
}