package com.self.activity.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="客户授权机构主键",description="客户授权机构主键")
public class OrgCustomerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_org_customer.customer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="客户ID",notes="客户ID")
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_org_customer.org_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="机构ID",notes="机构ID")
    private Integer orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_org_customer.customer_id
     *
     * @return the value of cu_org_customer.customer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_org_customer.customer_id
     *
     * @param customerId the value for cu_org_customer.customer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_org_customer.org_id
     *
     * @return the value of cu_org_customer.org_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_org_customer.org_id
     *
     * @param orgId the value for cu_org_customer.org_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
}