package com.self.activity.model;

import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
@ApiModel(value="关系人",description="关系人")
public class Relation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_relation.id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="关系Id",notes="关系ID")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_relation.custormer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="客户Id",notes="客户ID")
    private Long custormerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_relation.relation_customer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="关系客户Id",notes="关系客户ID")
    private Long relationCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_relation.relation_type_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="关系类型Id",notes="关系类型ID")
    private String relationTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_relation.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="版本",notes="版本")
    private Integer versionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_relation.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="创建人ID",notes="创建人ID")
    private Long createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_relation.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="创建时间",notes="创建人时间",hidden=true)
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_relation.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="更新人ID",notes="更新人Id")
    private Long lastUpdatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_relation.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="更新时间",notes="更新时间")
    private Date lastUpdatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_relation.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
	@ApiModelProperty(value="删除标志",notes="删除标志")
    private Boolean deletedFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_relation.id
     *
     * @return the value of cu_relation.id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_relation.id
     *
     * @param id the value for cu_relation.id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_relation.custormer_id
     *
     * @return the value of cu_relation.custormer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getCustormerId() {
        return custormerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_relation.custormer_id
     *
     * @param custormerId the value for cu_relation.custormer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCustormerId(Long custormerId) {
        this.custormerId = custormerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_relation.relation_customer_id
     *
     * @return the value of cu_relation.relation_customer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getRelationCustomerId() {
        return relationCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_relation.relation_customer_id
     *
     * @param relationCustomerId the value for cu_relation.relation_customer_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setRelationCustomerId(Long relationCustomerId) {
        this.relationCustomerId = relationCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_relation.relation_type_id
     *
     * @return the value of cu_relation.relation_type_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public String getRelationTypeId() {
        return relationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_relation.relation_type_id
     *
     * @param relationTypeId the value for cu_relation.relation_type_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setRelationTypeId(String relationTypeId) {
        this.relationTypeId = relationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_relation.version_no
     *
     * @return the value of cu_relation.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_relation.version_no
     *
     * @param versionNo the value for cu_relation.version_no
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_relation.created_by_id
     *
     * @return the value of cu_relation.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_relation.created_by_id
     *
     * @param createdById the value for cu_relation.created_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCreatedById(Long createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_relation.created_time
     *
     * @return the value of cu_relation.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_relation.created_time
     *
     * @param createdTime the value for cu_relation.created_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_relation.last_updated_by_id
     *
     * @return the value of cu_relation.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Long getLastUpdatedById() {
        return lastUpdatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_relation.last_updated_by_id
     *
     * @param lastUpdatedById the value for cu_relation.last_updated_by_id
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLastUpdatedById(Long lastUpdatedById) {
        this.lastUpdatedById = lastUpdatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_relation.last_updated_time
     *
     * @return the value of cu_relation.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_relation.last_updated_time
     *
     * @param lastUpdatedTime the value for cu_relation.last_updated_time
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_relation.deleted_flag
     *
     * @return the value of cu_relation.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_relation.deleted_flag
     *
     * @param deletedFlag the value for cu_relation.deleted_flag
     *
     * @mbggenerated Fri Nov 25 09:37:25 CST 2016
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }
}